<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-15J4PS7" failures="3" tests="15" name="Test" time="0.727" errors="0" timestamp="2023-07-16T19:35:36 IST">
  <testcase classname="FailedTestCaseExecution.Demo" name="Test1" time="0.052">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test1" time="0.014">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test1" time="0.006">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test1" time="0.015">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at FailedTestCaseExecution.Demo.Test1(Demo.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test2" time="0.01">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test2" time="0.019">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test2" time="0.008">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test2" time="0.017">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at FailedTestCaseExecution.Demo.Test2(Demo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test3" time="0.01"/>
  <testcase classname="FailedTestCaseExecution.UsingAssertions" name="Test1" time="0.057">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.UsingAssertions" name="Test1" time="0.005">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.UsingAssertions" name="Test1" time="0.008">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.UsingAssertions" name="Test1" time="0.035">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at FailedTestCaseExecution.UsingAssertions.Test1(UsingAssertions.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.UsingAssertions" name="Test2" time="0.024"/>
  <testcase classname="FailedTestCaseExecution.UsingAssertions" name="Test3" time="0.003"/>
</testsuite> <!-- Test -->
